name: Lint

on: [push, pull_request]

jobs:
  change-password-urls:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint Sort Order
      run: cat quirks/change-password-URLs.json | sed '1,1d' | sed '$d' | sort -c

  password-rules:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint Sort Order
      run: cat quirks/password-rules.json | grep "^    \"" | sort -c

  websites-shared-credentials:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Lint Sort Order
      run: ruby .github/workflows/lint-scripts/websites-shared-credentials-sort-order.rb