name: Lint

on: [push, pull_request]

jobs:
  all-json-valid:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Lint Valid Json
      run: |
        find quirks/ -name '*.json' -print0 -maxdepth 1 | while IFS= read -r -d '' filename; do
          echo "Validating $(basename "$filename")"
          python -mjson.tool "$filename" > /dev/null
        done

  change-password-urls:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Lint Sort Order
      run: cat quirks/change-password-URLs.json | sed '1,1d' | sed '$d' | sort -c

  password-rules:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Lint Sort Order
      run: cat quirks/password-rules.json | grep "^    \"" | sort -c

  websites-shared-credentials:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Lint Sort Order
      run: diff quirks/shared-credentials.json <(cat quirks/shared-credentials.json | jq --indent 4 'sort_by(.shared // .from)')
    - name: Lint Duplicates
      run: ruby .github/workflows/lint-scripts/websites-shared-credentials-duplicates.rb
    - name: Verify Generated Files
      run: ruby tools/convert-shared-credential-to-legacy-format.rb --verify

  validate-schemas:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - name: Install ajv-cli
      run: npm install -g ajv-cli
    - name: Validate JSONs against their schemas
      run: ./tools/validate-json-schemas.sh
